# Generated by Django 4.2.6 on 2024-01-19 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0003_category_background_color_category_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.URLField(default='asfasdfsd.com'),
            preserve_default=False,
        ),
    ]
